### ISSUE TITLE
.off() is not working properly for listeners added by .once()

### ISSUE THREAD

**Issue by aishikaty** [tunnckoCore/dush#8]
This doesn't seem to work as expected:
```javascript
const emitter = dush()
const hello = () => console.log("You shouldn't see this.")
emitter.once('test', hello)
emitter.off('test', hello)
emitter.emit('test')
```

**Comment by tunnckoCore** [comment]
Interesting. More and more bugs with that implemantation of `.off`. I think #7 is related to it too.

**Comment by tunnckoCore** [comment]
Actually, @aishikaty, it not make much sense to `off` something that is added by `once` because it is `off`ed by default, internally. That's the whole point of `once`.\

Nevermind, i got your logic, and it I fixed that, so now it is working. I'm going to push fixes in a bit.
